blank_issues_enabled: false
contact_links:
  - name: Forum Jeedom (support communautaire) / Jeedom Forum (community support)
    url: https://community.jeedom.com/
    about: Pour toute demande générale, merci d’utiliser le forum / For any general request, please use the forum
